### ISSUE TITLE
Thruway doesn't work when rpc was not registered

### ISSUE THREAD

**Issue by willbrid** [voryx/ThruwayBundle#82] opened 2018-04-19 04:23 UTC
Hi, 
I'm new in Thruway bundle. For me, Thruway is really great and simple for getting started. 

Please, i have a problem. I would like to handle this : when the rpc was not registered in the router, when called in a symfony controller, thruway no longer works and also symfony. So I have to restart.
(Symfony2.8)
Please, is there a way to handle this?

Thank you

**Comment by davidwdan** [comment] 2018-04-23 13:13
Can you provide the exact steps (with code) for us to reproduce this issue?

**Comment by willbrid** [comment] 2018-04-23 18:04
Hi Thank you very for your reply.
I would like to make a rpc call defined on the client side (javascript), from the controller via a call. I would like to handle the case where the client is not connected. In this case the call rpc is called on an undefined channel. However when I do the test for this case, the rpc blocks and the project does not work anymore.
My ultimate goal is to be able to check an online user for a given situation.

```php
private function checkUserOnline(User $user) 
{
     $client = $this->container->get('thruway.client');
     $patternUser = $this->container->getParameter('channel_user_pattern_online');
     $rpc = $patternUser . '.' . $user->getId();
     $response = false;
     $promise = $client->call($rpc, [])->then(
         function ($res) use (&$response) {
              if ($res[0] == null) {
                   return $res[0];
              }
              $response = true;
                  return $res[0];
              }
         );
         return $response;
 }
```

So when $rpc pattern it's not defined in client side how can i handle this.
Thank you very much.

**Comment by davidwdan** [comment] 2018-04-23 21:33
You should be able to just return a promise:  

```PHP
private function checkUserOnline(User $user) 
{
     $client = $this->container->get('thruway.client');
     $patternUser = $this->container->getParameter('channel_user_pattern_online');
    
     if ($patternUser) { 
           $rpc = $patternUser . '.' . $user->getId();

           return $client->call($rpc, []);
     }
 }
```

**Comment by willbrid** [comment] 2018-04-24 07:33
Hi Thank you very much for your reply.

I tested your solution. my projet doesn't crash anymore but when i display this promise i have this with var_dump : 

``
object(React\Promise\Promise)#575 (6) { ["canceller":"React\Promise\Promise":private]=> NULL ["result":"React\Promise\Promise":private]=> NULL ["handlers":"React\Promise\Promise":private]=> array(0) { } ["progressHandlers":"React\Promise\Promise":private]=> array(0) { } ["requiredCancelRequests":"React\Promise\Promise":private]=> int(0) ["cancelRequests":"React\Promise\Promise":private]=> int(0) } 
``

Event if the rpc is define in the client side (javascript) like this : 

```javascript
 function response(args) {
     return "YES";
 }
 var id=1;
 session.register('channel_user_pattern_online' + id, response);
```
When i return the promise, i have the same result of promise as above. I would like to have a way to return a boolean that will allow me to know if the user is online or not, based on the fact that he has recorded a rpc channel or not.
Thank you very much.

**Comment by davidwdan** [comment] 2018-04-24 11:55
A promise is a future value, so you can't var_dump it to see the values.  You can read more about how promises work here: https://github.com/reactphp/promise

Returning a promise should work.  If you only want to know if the rpc called failed or not, you can try something like this:

```PHP
return $client->call($rpc, [])->then(
    function(){
        return "YES";
    }, 
    function(){
        return "NO";
    });

```

**Comment by willbrid** [comment] 2018-04-25 08:33
Hi Thank you very much for your reply. 

Forgive me : but return a promise did not help me for my intention. Is there a way to have a state of this rpc call ? or to catch a response of callback ? 

Thank you very much.

**Comment by davidwdan** [comment] 2018-04-25 11:57
The only way to return an async value is by returning a promise, which is what `$client->call($rpc, [])` returns.  

What happened when you returned a promise?

**Comment by willbrid** [comment] 2018-04-26 08:07
Hi Thank you very much for your reply.

Nothing happen : i received a promise object. In fact i  would like to assign a value when a promise fails to allow me to trace this state in my controller. I would like to have something like this in my controller.

in php controller file
```php
public function sendAction(){
    $user = $this->getUser()->getId();
    if($this->get('service_name')->checkUserOnline($user){
        doSomething();
        //......
    }
    
    //....
}
```

in php service file
```php
private function checkUserOnline(User $user) 
{
     $client = $this->container->get('thruway.client');
     $patternUser = $this->container->getParameter('channel_user_pattern_online');
     $rpc = $patternUser . '.' . $user->getId();
     return $client->call($rpc, []);
  
 }
```

And then in js file (with autobahn library), i have something like this : 
```javascript
function response(args) {
     return "YES";
 }
 var id=1;
 session.register('channel_user_pattern_online' + id, response);
```

So if i call the rpc registered in client side, it would walk. But if there is not connection with server, the client cannot registered the rpc and the call rpc would failed, so i would like to handle this failure and do something else. May be i'm doing wrong or it is not the correct way to achieve this.
Please, do you have an idea ?

Thank you very much

**Comment by davidwdan** [comment] 2018-04-26 12:24
You're still trying to mix async and sync code.  This lib will allow you to block until the promise has resolved: https://github.com/clue/php-block-react 

```PHP
private function checkUserOnline(User $user) 
{
     $client = $this->container->get('thruway.client');
     $patternUser = $this->container->getParameter('channel_user_pattern_online');
     $rpc = $patternUser . '.' . $user->getId();
      
       try {
            $result \Clue\React\Block\await($client->call($rpc, []));  
        } catch (TimeoutException $expected) {
            // do something if it fails
        }
      
        return $result;
 }
```

I'm going to close this issue because it doesn't appear to be a problem with the RPC.

**Closed by davidwdan** 2018-04-26 12:24 UTC
